{{- range $appName, $appValues := .Values.applications }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  labels:
    app: {{ $appName }}
spec:
  {{- if not $appValues.autoscaling.enabled }}
  replicas: {{ $appValues.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      {{- with $appValues.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ $appName }}
    spec:
      {{- with $appValues.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $appValues.podSecurityContext | nindent 8 }}
      {{- include "library.containers" $appValues | nindent 6 }}

      {{- if $appValues.volumes }}
      volumes:
        {{- toYaml $appValues.volumes | nindent 8 }}
      {{- end }}
        
      {{- with $appValues.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $appValues.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $appValues.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
