{{- range $appName, $appValues := .Values.applications }}
{{- if $appValues.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $appName }}
  namespace: {{ $appValues.namespace }}
  labels:
    app: {{ $appName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $appName }}
  minReplicas: {{ $appValues.autoscaling.minReplicas }}
  maxReplicas: {{ $appValues.autoscaling.maxReplicas }}
  metrics:
    {{- if $appValues.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $appValues.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $appValues.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $appValues.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
