{{- range $appName, $appValues := .Values.applications }}
{{- if $appValues.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}
  labels:
    app: {{ $appName }}
spec:
  type: {{ $appValues.service.type }}
  ports:
    {{- range $appValues.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    app: {{ $appName }}
{{- end }}
{{- end }}
