{{/*
    Within a deployment, someone can have multiple containers. This approach allows one to define multiple containers
    within the deployment. It can also include the sidecars
*/}}
{{- define "library.containers" -}}
containers:
  {{- range .containers }}
  - name: {{ .name }}
    image: "{{ .image }}"
    imagePullPolicy: {{ .imagePullPolicy | default "Always" }}
    securityContext:
      {{- if .securityContext }}
      {{- toYaml .securityContext | nindent 6 }}
      {{- else }}
      runAsNonRoot: true
      runAsUser: 1000  # Default UID, consider making this dynamic or required in values.yaml
    {{- end }}
    {{- if .livenessProbe }}
    livenessProbe:
      {{- toYaml .livenessProbe | nindent 6 }}
    {{- end }}
    {{- if .ports }}
    ports:
      {{- range .ports }}
      - name: {{ .name }}
        containerPort: {{ .containerPort }}
      {{- end }}
    {{ end }}
    {{- if .env }}
    env:
      {{- range .env }}
      - name: {{ .name }}
        value: {{ .value | quote }}
      {{- end }}
    {{- end }}
    {{- if .configMapNames}}
    envFrom:
    {{- range .configMapNames }}
      - configMapRef:
        name: {{ . }}
    {{- end }}
    {{- end }}
    resources:
      {{- if not .resources }}
        {{- fail "Resource limits and requests must be specified for all containers." }}
      {{- else }}
        {{- toYaml .resources | nindent 6 }}
      {{- end }}
    {{- if .volumeMounts }}
    volumeMounts:
      {{- range .volumeMounts }}
      - name: {{ .name }}
        mountPath: {{ .mountPath }}
        readOnly: {{ .readOnly | default false }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
