name: Checkov

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: base
          framework: helm 
          # TODO: With time, these should be returned & possibly write an article about it
          skip_check: CKV_K8S_40,CKV_K8S_43,CKV_K8S_9,CKV_K8S_38